# Generated by Django 3.1.7 on 2021-04-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_team_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='code',
            new_name='room_id',
        ),
    ]
