# Generated by Django 3.1.7 on 2021-04-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210415_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='room_id',
        ),
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
