# Generated by Django 3.1.7 on 2021-04-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210415_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default='', max_length=6)),
                ('event_name', models.CharField(default='', max_length=24, unique=True)),
                ('team_a', models.CharField(default='', max_length=50)),
                ('team_b', models.CharField(default='', max_length=50)),
                ('team_c', models.CharField(default='', max_length=50)),
                ('team_d', models.CharField(default='', max_length=50)),
                ('winner_ab', models.CharField(default='', max_length=50)),
                ('winner_cd', models.CharField(default='', max_length=50)),
                ('event_winner', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Bracket',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
