# Generated by Django 3.1.7 on 2021-04-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_team_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='code',
            new_name='room_code',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
