# Generated by Django 3.1.7 on 2021-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210416_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='winner_ab',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='winner_cd',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
